name: 'Redox'
on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
    build:
        if: github.repository_owner == 'vekexasia'
        uses: ./.github/workflows/main.yml
        secrets: inherit
        with:
            keyboard: '["redox/default"]'
            alphas: '["QWERTY"]'
            nav: '["vi"]'

